# TK8710 HAL JTOOL Makefile for Windows

CC = gcc
AR = ar

CFLAGS = -Wall -Wextra -Wno-unused-parameter -O2
CFLAGS += -DPLATFORM_JTOOL -DWIN32_LEAN_AND_MEAN -D__USE_MINGW_ANSI_STDIO=1

INC = -I./inc -I./inc/driver -I./inc/trm -I./inc/phy -I./port -I./port/jtool

JTOOL_DLL = port/jtool/x64/jtool.dll
JTOOL_DEF = $(BUILD_DIR)/jtool.def
JTOOL_LIB = $(BUILD_DIR)/libjtool_generated.a
LDFLAGS = $(JTOOL_LIB) -lwinmm

BUILD_DIR = build_jtool

PHY_SRC = \
	src/phy/phy_api.c \
	src/phy/phy_irq.c \
	src/phy/phy_regs.c \
	src/phy/phy_log.c \
	src/phy/phy_test.c

HAL_SRC = \
	src/hal/hal_api.c \
	src/hal/hal_cb.c \
	src/hal/hal_status.c

TRM_V02_SRC = \
	src/trm/trm_queue.c \
	src/trm/phy_data.c \
	src/trm/phy_cfg.c \
	src/trm/phy_stat.c

LEGACY_SRC = \
	src/driver/tk8710_log.c \
	src/driver/tk8710_core.c \
	src/driver/tk8710_config.c \
	src/driver/tk8710_irq.c \
	src/trm/trm_core.c \
	src/trm/trm_beam.c \
	src/trm/trm_data.c \
	src/trm/trm_satellite.c \
	src/trm/trm_mac_parser.c \
	src/trm/trm_slot.c \
	src/trm/trm_freq.c \
	src/trm/trm_power.c \
	src/trm/trm_log.c \
	port/jtool/port_jtool.c

ALL_SRC = $(PHY_SRC) $(HAL_SRC) $(TRM_V02_SRC) $(LEGACY_SRC)
ALL_OBJ = $(patsubst %.c,$(BUILD_DIR)/%.o,$(ALL_SRC))

LIB_TARGET = $(BUILD_DIR)/libtk8710_hal.a
API_SMOKE_TEST = $(BUILD_DIR)/test_hal_phy_api.o
DRIVER_TEST_SRC = $(wildcard test/DriverTest/*.c)
DRIVER_TEST_EXE = $(patsubst test/DriverTest/%.c,$(BUILD_DIR)/%.exe,$(DRIVER_TEST_SRC))
RF_CAL_TCP_SERVER_SRC = test/DriverTest/support/rf_cal_tcp_server.c
RF_CAL_TCP_TEST_SRC = test/DriverTest/support/test_rf_cal_tcp_server.c
RF_CAL_TCP_TEST_EXE = $(BUILD_DIR)/test_rf_cal_tcp_server.exe
ACM_GAIN_TEST_SRC = test/DriverTest/test_acm_gain_v2.c
ACM_GAIN_TEST_EXE = $(BUILD_DIR)/test_acm_gain_v2.exe

.PHONY: all clean lib tests driver_tests rf_cal_tcp_tests acm_gain_tests copy_dll

all: lib tests

lib: $(LIB_TARGET)

tests: $(API_SMOKE_TEST)

driver_tests: $(DRIVER_TEST_EXE) copy_dll

rf_cal_tcp_tests: $(RF_CAL_TCP_TEST_EXE)
	$(RF_CAL_TCP_TEST_EXE)

acm_gain_tests: $(ACM_GAIN_TEST_EXE)
	$(ACM_GAIN_TEST_EXE)

$(BUILD_DIR):
	@if not exist $(BUILD_DIR) mkdir $(BUILD_DIR)
	@if not exist $(BUILD_DIR)\src mkdir $(BUILD_DIR)\src
	@if not exist $(BUILD_DIR)\src\phy mkdir $(BUILD_DIR)\src\phy
	@if not exist $(BUILD_DIR)\src\hal mkdir $(BUILD_DIR)\src\hal
	@if not exist $(BUILD_DIR)\src\trm mkdir $(BUILD_DIR)\src\trm
	@if not exist $(BUILD_DIR)\src\driver mkdir $(BUILD_DIR)\src\driver
	@if not exist $(BUILD_DIR)\port mkdir $(BUILD_DIR)\port
	@if not exist $(BUILD_DIR)\port\jtool mkdir $(BUILD_DIR)\port\jtool

$(BUILD_DIR)/%.o: %.c | $(BUILD_DIR)
	$(CC) $(CFLAGS) $(INC) -c $< -o $@

$(JTOOL_DEF): $(JTOOL_DLL) | $(BUILD_DIR)
	@gendef - $(JTOOL_DLL) > $(JTOOL_DEF)

$(JTOOL_LIB): $(JTOOL_DEF)
	dlltool -d $(JTOOL_DEF) -D jtool.dll -l $(JTOOL_LIB)

$(LIB_TARGET): $(ALL_OBJ)
	$(AR) rcs $@ $^

$(API_SMOKE_TEST): test/example/test_hal_phy_api.c | $(BUILD_DIR)
	$(CC) $(CFLAGS) $(INC) -c $< -o $@

$(BUILD_DIR)/%.exe: test/DriverTest/%.c $(LIB_TARGET) $(JTOOL_LIB) | $(BUILD_DIR)
	$(CC) $(CFLAGS) $(INC) -I./test/DriverTest $< $(LIB_TARGET) $(LDFLAGS) -o $@

$(BUILD_DIR)/Test8710RFTxTone.exe: test/DriverTest/Test8710RFTxTone.c $(RF_CAL_TCP_SERVER_SRC) $(LIB_TARGET) $(JTOOL_LIB) | $(BUILD_DIR)
	$(CC) $(CFLAGS) $(INC) -I./test/DriverTest -I./test/DriverTest/support $< $(RF_CAL_TCP_SERVER_SRC) $(LIB_TARGET) $(LDFLAGS) -lws2_32 -o $@

$(BUILD_DIR)/Test8710RFTest.exe: test/DriverTest/Test8710RFTest.c $(RF_CAL_TCP_SERVER_SRC) $(LIB_TARGET) $(JTOOL_LIB) | $(BUILD_DIR)
	$(CC) $(CFLAGS) $(INC) -I./test/DriverTest -I./test/DriverTest/support $< $(RF_CAL_TCP_SERVER_SRC) $(LIB_TARGET) $(LDFLAGS) -lws2_32 -o $@

$(RF_CAL_TCP_TEST_EXE): $(RF_CAL_TCP_TEST_SRC) $(RF_CAL_TCP_SERVER_SRC) | $(BUILD_DIR)
	$(CC) $(CFLAGS) -I./test/DriverTest/support $(RF_CAL_TCP_TEST_SRC) $(RF_CAL_TCP_SERVER_SRC) -lws2_32 -o $@

$(ACM_GAIN_TEST_EXE): $(ACM_GAIN_TEST_SRC) src/driver/tk8710_config.c | $(BUILD_DIR)
	$(CC) $(CFLAGS) -O0 -ffunction-sections -fdata-sections $(INC) -I. $< -Wl,--gc-sections -o $@

copy_dll: $(LIB_TARGET)
	@copy port\jtool\x64\jtool.dll $(BUILD_DIR)\ >nul 2>&1 || echo.

clean:
	@if exist $(BUILD_DIR) rmdir /s /q $(BUILD_DIR)
